//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class Ballance2_UI_Components_DialogResultWrap
{
	public static void Register(LuaState L)
	{
		L.BeginEnum(typeof(Ballance2.UI.Components.DialogResult));
		L.RegVar("None", get_None, null);
		L.RegVar("OK", get_OK, null);
		L.RegVar("Cancel", get_Cancel, null);
		L.RegVar("Third", get_Third, null);
		L.RegFunction("IntToEnum", IntToEnum);
		L.EndEnum();
		TypeTraits<Ballance2.UI.Components.DialogResult>.Check = CheckType;
		StackTraits<Ballance2.UI.Components.DialogResult>.Push = Push;
	}

	static void Push(IntPtr L, Ballance2.UI.Components.DialogResult arg)
	{
		ToLua.Push(L, arg);
	}

	static bool CheckType(IntPtr L, int pos)
	{
		return TypeChecker.CheckEnumType(typeof(Ballance2.UI.Components.DialogResult), L, pos);
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_None(IntPtr L)
	{
		ToLua.Push(L, Ballance2.UI.Components.DialogResult.None);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_OK(IntPtr L)
	{
		ToLua.Push(L, Ballance2.UI.Components.DialogResult.OK);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Cancel(IntPtr L)
	{
		ToLua.Push(L, Ballance2.UI.Components.DialogResult.Cancel);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Third(IntPtr L)
	{
		ToLua.Push(L, Ballance2.UI.Components.DialogResult.Third);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int IntToEnum(IntPtr L)
	{
		int arg0 = (int)LuaDLL.lua_tonumber(L, 1);
		Ballance2.UI.Components.DialogResult o = (Ballance2.UI.Components.DialogResult)arg0;
		ToLua.Push(L, o);
		return 1;
	}
}

