//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class Ballance2_GameUIMgrWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(Ballance2.GameUIMgr), typeof(UnityEngine.MonoBehaviour));
		L.RegFunction("ExitGameClear", ExitGameClear);
		L.RegFunction("FadeOut", FadeOut);
		L.RegFunction("FadeIn", FadeIn);
		L.RegFunction("GetStandardUIMaker", GetStandardUIMaker);
		L.RegFunction("ShowDialog", ShowDialog);
		L.RegFunction("ShowDialogThreeChoice", ShowDialogThreeChoice);
		L.RegFunction("IsDialogClosed", IsDialogClosed);
		L.RegFunction("GetLastDialogResult", GetLastDialogResult);
		L.RegFunction("GoMenuPage", GoMenuPage);
		L.RegFunction("HideMenuPage", HideMenuPage);
		L.RegFunction("BackForntMenuPage", BackForntMenuPage);
		L.RegFunction("HideUIForAWhile", HideUIForAWhile);
		L.RegFunction("ReshowUI", ReshowUI);
		L.RegFunction("SetStartNoBlack", SetStartNoBlack);
		L.RegFunction("SetStartBlack", SetStartBlack);
		L.RegFunction("__eq", op_Equality);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("uiHost", get_uiHost, set_uiHost);
		L.RegVar("dbgCam", get_dbgCam, set_dbgCam);
		L.RegVar("UIFadeHlper", get_UIFadeHlper, set_UIFadeHlper);
		L.RegVar("Canvas", get_Canvas, set_Canvas);
		L.RegVar("MenuPageTemplate", get_MenuPageTemplate, set_MenuPageTemplate);
		L.RegVar("MenuPageCleanTemplate", get_MenuPageCleanTemplate, set_MenuPageCleanTemplate);
		L.RegVar("SliderPrefabTemplate", get_SliderPrefabTemplate, set_SliderPrefabTemplate);
		L.RegVar("TextPrefabTemplate", get_TextPrefabTemplate, set_TextPrefabTemplate);
		L.RegVar("TogglePrefabTemplate", get_TogglePrefabTemplate, set_TogglePrefabTemplate);
		L.RegVar("DropDownPrefabTemplate", get_DropDownPrefabTemplate, set_DropDownPrefabTemplate);
		L.RegVar("BtnMulitTemplate", get_BtnMulitTemplate, set_BtnMulitTemplate);
		L.RegVar("BtnMainMenuTemplate", get_BtnMainMenuTemplate, set_BtnMainMenuTemplate);
		L.RegVar("BtnMainBackTemplate", get_BtnMainBackTemplate, set_BtnMainBackTemplate);
		L.RegVar("BtnLevTemplate", get_BtnLevTemplate, set_BtnLevTemplate);
		L.RegVar("TextTitlePerfab", get_TextTitlePerfab, set_TextTitlePerfab);
		L.RegVar("MenuDialog2", get_MenuDialog2, set_MenuDialog2);
		L.RegVar("MenuDialog3", get_MenuDialog3, set_MenuDialog3);
		L.RegVar("GameBulider", get_GameBulider, set_GameBulider);
		L.RegVar("UIMaker", get_UIMaker, null);
		L.RegVar("LastShowMenuPage", get_LastShowMenuPage, null);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int ExitGameClear(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			Ballance2.GameUIMgr obj = (Ballance2.GameUIMgr)ToLua.CheckObject<Ballance2.GameUIMgr>(L, 1);
			obj.ExitGameClear();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int FadeOut(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			Ballance2.GameUIMgr obj = (Ballance2.GameUIMgr)ToLua.CheckObject<Ballance2.GameUIMgr>(L, 1);
			obj.FadeOut();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int FadeIn(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			Ballance2.GameUIMgr obj = (Ballance2.GameUIMgr)ToLua.CheckObject<Ballance2.GameUIMgr>(L, 1);
			obj.FadeIn();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetStandardUIMaker(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			Ballance2.GameUIMgr obj = (Ballance2.GameUIMgr)ToLua.CheckObject<Ballance2.GameUIMgr>(L, 1);
			Ballance2.GameUIMgr.StandardUIMaker o = obj.GetStandardUIMaker();
			ToLua.PushObject(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int ShowDialog(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 6);
			Ballance2.GameUIMgr obj = (Ballance2.GameUIMgr)ToLua.CheckObject<Ballance2.GameUIMgr>(L, 1);
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			string arg1 = ToLua.CheckString(L, 3);
			string arg2 = ToLua.CheckString(L, 4);
			string arg3 = ToLua.CheckString(L, 5);
			string arg4 = ToLua.CheckString(L, 6);
			obj.ShowDialog(arg0, arg1, arg2, arg3, arg4);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int ShowDialogThreeChoice(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 7);
			Ballance2.GameUIMgr obj = (Ballance2.GameUIMgr)ToLua.CheckObject<Ballance2.GameUIMgr>(L, 1);
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			string arg1 = ToLua.CheckString(L, 3);
			string arg2 = ToLua.CheckString(L, 4);
			string arg3 = ToLua.CheckString(L, 5);
			string arg4 = ToLua.CheckString(L, 6);
			string arg5 = ToLua.CheckString(L, 7);
			obj.ShowDialogThreeChoice(arg0, arg1, arg2, arg3, arg4, arg5);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int IsDialogClosed(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			Ballance2.GameUIMgr obj = (Ballance2.GameUIMgr)ToLua.CheckObject<Ballance2.GameUIMgr>(L, 1);
			bool o = obj.IsDialogClosed();
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetLastDialogResult(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			Ballance2.GameUIMgr obj = (Ballance2.GameUIMgr)ToLua.CheckObject<Ballance2.GameUIMgr>(L, 1);
			Ballance2.UI.Components.DialogResult o = obj.GetLastDialogResult();
			ToLua.Push(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GoMenuPage(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 2)
			{
				Ballance2.GameUIMgr obj = (Ballance2.GameUIMgr)ToLua.CheckObject<Ballance2.GameUIMgr>(L, 1);
				Ballance2.UI.UIPage arg0 = (Ballance2.UI.UIPage)ToLua.CheckObject<Ballance2.UI.UIPage>(L, 2);
				obj.GoMenuPage(arg0);
				return 0;
			}
			else if (count == 3)
			{
				Ballance2.GameUIMgr obj = (Ballance2.GameUIMgr)ToLua.CheckObject<Ballance2.GameUIMgr>(L, 1);
				string arg0 = ToLua.CheckString(L, 2);
				string arg1 = ToLua.CheckString(L, 3);
				obj.GoMenuPage(arg0, arg1);
				return 0;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to method: Ballance2.GameUIMgr.GoMenuPage");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int HideMenuPage(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 2 && TypeChecker.CheckTypes<string>(L, 2))
			{
				Ballance2.GameUIMgr obj = (Ballance2.GameUIMgr)ToLua.CheckObject<Ballance2.GameUIMgr>(L, 1);
				string arg0 = ToLua.ToString(L, 2);
				obj.HideMenuPage(arg0);
				return 0;
			}
			else if (count == 2 && TypeChecker.CheckTypes<Ballance2.UI.UIPage>(L, 2))
			{
				Ballance2.GameUIMgr obj = (Ballance2.GameUIMgr)ToLua.CheckObject<Ballance2.GameUIMgr>(L, 1);
				Ballance2.UI.UIPage arg0 = (Ballance2.UI.UIPage)ToLua.ToObject(L, 2);
				obj.HideMenuPage(arg0);
				return 0;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to method: Ballance2.GameUIMgr.HideMenuPage");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int BackForntMenuPage(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			Ballance2.GameUIMgr obj = (Ballance2.GameUIMgr)ToLua.CheckObject<Ballance2.GameUIMgr>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			obj.BackForntMenuPage(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int HideUIForAWhile(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			Ballance2.GameUIMgr obj = (Ballance2.GameUIMgr)ToLua.CheckObject<Ballance2.GameUIMgr>(L, 1);
			obj.HideUIForAWhile();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int ReshowUI(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			Ballance2.GameUIMgr obj = (Ballance2.GameUIMgr)ToLua.CheckObject<Ballance2.GameUIMgr>(L, 1);
			obj.ReshowUI();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetStartNoBlack(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 0);
			Ballance2.GameUIMgr.SetStartNoBlack();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetStartBlack(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 0);
			Ballance2.GameUIMgr.SetStartBlack();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int op_Equality(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.Object arg0 = (UnityEngine.Object)ToLua.ToObject(L, 1);
			UnityEngine.Object arg1 = (UnityEngine.Object)ToLua.ToObject(L, 2);
			bool o = arg0 == arg1;
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_uiHost(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Ballance2.GameUIMgr obj = (Ballance2.GameUIMgr)o;
			UnityEngine.GameObject ret = obj.uiHost;
			ToLua.PushSealed(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index uiHost on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_dbgCam(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Ballance2.GameUIMgr obj = (Ballance2.GameUIMgr)o;
			UnityEngine.GameObject ret = obj.dbgCam;
			ToLua.PushSealed(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index dbgCam on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_UIFadeHlper(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Ballance2.GameUIMgr obj = (Ballance2.GameUIMgr)o;
			Ballance2.UI.Utils.FadeHlper ret = obj.UIFadeHlper;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index UIFadeHlper on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Canvas(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Ballance2.GameUIMgr obj = (Ballance2.GameUIMgr)o;
			UnityEngine.GameObject ret = obj.Canvas;
			ToLua.PushSealed(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index Canvas on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_MenuPageTemplate(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Ballance2.GameUIMgr obj = (Ballance2.GameUIMgr)o;
			UnityEngine.GameObject ret = obj.MenuPageTemplate;
			ToLua.PushSealed(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index MenuPageTemplate on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_MenuPageCleanTemplate(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Ballance2.GameUIMgr obj = (Ballance2.GameUIMgr)o;
			UnityEngine.GameObject ret = obj.MenuPageCleanTemplate;
			ToLua.PushSealed(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index MenuPageCleanTemplate on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_SliderPrefabTemplate(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Ballance2.GameUIMgr obj = (Ballance2.GameUIMgr)o;
			UnityEngine.GameObject ret = obj.SliderPrefabTemplate;
			ToLua.PushSealed(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index SliderPrefabTemplate on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_TextPrefabTemplate(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Ballance2.GameUIMgr obj = (Ballance2.GameUIMgr)o;
			UnityEngine.GameObject ret = obj.TextPrefabTemplate;
			ToLua.PushSealed(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index TextPrefabTemplate on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_TogglePrefabTemplate(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Ballance2.GameUIMgr obj = (Ballance2.GameUIMgr)o;
			UnityEngine.GameObject ret = obj.TogglePrefabTemplate;
			ToLua.PushSealed(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index TogglePrefabTemplate on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_DropDownPrefabTemplate(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Ballance2.GameUIMgr obj = (Ballance2.GameUIMgr)o;
			UnityEngine.GameObject ret = obj.DropDownPrefabTemplate;
			ToLua.PushSealed(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index DropDownPrefabTemplate on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_BtnMulitTemplate(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Ballance2.GameUIMgr obj = (Ballance2.GameUIMgr)o;
			UnityEngine.GameObject ret = obj.BtnMulitTemplate;
			ToLua.PushSealed(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index BtnMulitTemplate on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_BtnMainMenuTemplate(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Ballance2.GameUIMgr obj = (Ballance2.GameUIMgr)o;
			UnityEngine.GameObject ret = obj.BtnMainMenuTemplate;
			ToLua.PushSealed(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index BtnMainMenuTemplate on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_BtnMainBackTemplate(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Ballance2.GameUIMgr obj = (Ballance2.GameUIMgr)o;
			UnityEngine.GameObject ret = obj.BtnMainBackTemplate;
			ToLua.PushSealed(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index BtnMainBackTemplate on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_BtnLevTemplate(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Ballance2.GameUIMgr obj = (Ballance2.GameUIMgr)o;
			UnityEngine.GameObject ret = obj.BtnLevTemplate;
			ToLua.PushSealed(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index BtnLevTemplate on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_TextTitlePerfab(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Ballance2.GameUIMgr obj = (Ballance2.GameUIMgr)o;
			UnityEngine.GameObject ret = obj.TextTitlePerfab;
			ToLua.PushSealed(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index TextTitlePerfab on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_MenuDialog2(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Ballance2.GameUIMgr obj = (Ballance2.GameUIMgr)o;
			Ballance2.UI.Components.DialogUI ret = obj.MenuDialog2;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index MenuDialog2 on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_MenuDialog3(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Ballance2.GameUIMgr obj = (Ballance2.GameUIMgr)o;
			Ballance2.UI.Components.DialogUI ret = obj.MenuDialog3;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index MenuDialog3 on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_GameBulider(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Ballance2.GameUIMgr obj = (Ballance2.GameUIMgr)o;
			Ballance2.GameBulider ret = obj.GameBulider;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index GameBulider on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_UIMaker(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Ballance2.GameUIMgr obj = (Ballance2.GameUIMgr)o;
			Ballance2.GameUIMgr.StandardUIMaker ret = obj.UIMaker;
			ToLua.PushObject(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index UIMaker on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_LastShowMenuPage(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Ballance2.GameUIMgr obj = (Ballance2.GameUIMgr)o;
			string ret = obj.LastShowMenuPage;
			LuaDLL.lua_pushstring(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index LastShowMenuPage on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_uiHost(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Ballance2.GameUIMgr obj = (Ballance2.GameUIMgr)o;
			UnityEngine.GameObject arg0 = (UnityEngine.GameObject)ToLua.CheckObject(L, 2, typeof(UnityEngine.GameObject));
			obj.uiHost = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index uiHost on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_dbgCam(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Ballance2.GameUIMgr obj = (Ballance2.GameUIMgr)o;
			UnityEngine.GameObject arg0 = (UnityEngine.GameObject)ToLua.CheckObject(L, 2, typeof(UnityEngine.GameObject));
			obj.dbgCam = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index dbgCam on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_UIFadeHlper(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Ballance2.GameUIMgr obj = (Ballance2.GameUIMgr)o;
			Ballance2.UI.Utils.FadeHlper arg0 = (Ballance2.UI.Utils.FadeHlper)ToLua.CheckObject<Ballance2.UI.Utils.FadeHlper>(L, 2);
			obj.UIFadeHlper = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index UIFadeHlper on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_Canvas(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Ballance2.GameUIMgr obj = (Ballance2.GameUIMgr)o;
			UnityEngine.GameObject arg0 = (UnityEngine.GameObject)ToLua.CheckObject(L, 2, typeof(UnityEngine.GameObject));
			obj.Canvas = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index Canvas on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_MenuPageTemplate(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Ballance2.GameUIMgr obj = (Ballance2.GameUIMgr)o;
			UnityEngine.GameObject arg0 = (UnityEngine.GameObject)ToLua.CheckObject(L, 2, typeof(UnityEngine.GameObject));
			obj.MenuPageTemplate = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index MenuPageTemplate on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_MenuPageCleanTemplate(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Ballance2.GameUIMgr obj = (Ballance2.GameUIMgr)o;
			UnityEngine.GameObject arg0 = (UnityEngine.GameObject)ToLua.CheckObject(L, 2, typeof(UnityEngine.GameObject));
			obj.MenuPageCleanTemplate = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index MenuPageCleanTemplate on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_SliderPrefabTemplate(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Ballance2.GameUIMgr obj = (Ballance2.GameUIMgr)o;
			UnityEngine.GameObject arg0 = (UnityEngine.GameObject)ToLua.CheckObject(L, 2, typeof(UnityEngine.GameObject));
			obj.SliderPrefabTemplate = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index SliderPrefabTemplate on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_TextPrefabTemplate(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Ballance2.GameUIMgr obj = (Ballance2.GameUIMgr)o;
			UnityEngine.GameObject arg0 = (UnityEngine.GameObject)ToLua.CheckObject(L, 2, typeof(UnityEngine.GameObject));
			obj.TextPrefabTemplate = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index TextPrefabTemplate on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_TogglePrefabTemplate(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Ballance2.GameUIMgr obj = (Ballance2.GameUIMgr)o;
			UnityEngine.GameObject arg0 = (UnityEngine.GameObject)ToLua.CheckObject(L, 2, typeof(UnityEngine.GameObject));
			obj.TogglePrefabTemplate = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index TogglePrefabTemplate on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_DropDownPrefabTemplate(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Ballance2.GameUIMgr obj = (Ballance2.GameUIMgr)o;
			UnityEngine.GameObject arg0 = (UnityEngine.GameObject)ToLua.CheckObject(L, 2, typeof(UnityEngine.GameObject));
			obj.DropDownPrefabTemplate = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index DropDownPrefabTemplate on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_BtnMulitTemplate(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Ballance2.GameUIMgr obj = (Ballance2.GameUIMgr)o;
			UnityEngine.GameObject arg0 = (UnityEngine.GameObject)ToLua.CheckObject(L, 2, typeof(UnityEngine.GameObject));
			obj.BtnMulitTemplate = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index BtnMulitTemplate on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_BtnMainMenuTemplate(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Ballance2.GameUIMgr obj = (Ballance2.GameUIMgr)o;
			UnityEngine.GameObject arg0 = (UnityEngine.GameObject)ToLua.CheckObject(L, 2, typeof(UnityEngine.GameObject));
			obj.BtnMainMenuTemplate = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index BtnMainMenuTemplate on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_BtnMainBackTemplate(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Ballance2.GameUIMgr obj = (Ballance2.GameUIMgr)o;
			UnityEngine.GameObject arg0 = (UnityEngine.GameObject)ToLua.CheckObject(L, 2, typeof(UnityEngine.GameObject));
			obj.BtnMainBackTemplate = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index BtnMainBackTemplate on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_BtnLevTemplate(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Ballance2.GameUIMgr obj = (Ballance2.GameUIMgr)o;
			UnityEngine.GameObject arg0 = (UnityEngine.GameObject)ToLua.CheckObject(L, 2, typeof(UnityEngine.GameObject));
			obj.BtnLevTemplate = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index BtnLevTemplate on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_TextTitlePerfab(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Ballance2.GameUIMgr obj = (Ballance2.GameUIMgr)o;
			UnityEngine.GameObject arg0 = (UnityEngine.GameObject)ToLua.CheckObject(L, 2, typeof(UnityEngine.GameObject));
			obj.TextTitlePerfab = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index TextTitlePerfab on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_MenuDialog2(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Ballance2.GameUIMgr obj = (Ballance2.GameUIMgr)o;
			Ballance2.UI.Components.DialogUI arg0 = (Ballance2.UI.Components.DialogUI)ToLua.CheckObject<Ballance2.UI.Components.DialogUI>(L, 2);
			obj.MenuDialog2 = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index MenuDialog2 on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_MenuDialog3(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Ballance2.GameUIMgr obj = (Ballance2.GameUIMgr)o;
			Ballance2.UI.Components.DialogUI arg0 = (Ballance2.UI.Components.DialogUI)ToLua.CheckObject<Ballance2.UI.Components.DialogUI>(L, 2);
			obj.MenuDialog3 = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index MenuDialog3 on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_GameBulider(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Ballance2.GameUIMgr obj = (Ballance2.GameUIMgr)o;
			Ballance2.GameBulider arg0 = (Ballance2.GameBulider)ToLua.CheckObject<Ballance2.GameBulider>(L, 2);
			obj.GameBulider = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index GameBulider on a nil value");
		}
	}
}

