//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class Ballance2_UI_UIElements_UIDropDownWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(Ballance2.UI.UIElements.UIDropDown), typeof(Ballance2.UI.UIElement));
		L.RegFunction("OnInit", OnInit);
		L.RegFunction("StartSet", StartSet);
		L.RegFunction("__eq", op_Equality);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("Dropdown", get_Dropdown, null);
		L.RegVar("Text", get_Text, set_Text);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int OnInit(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			Ballance2.UI.UIElements.UIDropDown obj = (Ballance2.UI.UIElements.UIDropDown)ToLua.CheckObject<Ballance2.UI.UIElements.UIDropDown>(L, 1);
			obj.OnInit();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int StartSet(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			Ballance2.UI.UIElements.UIDropDown obj = (Ballance2.UI.UIElements.UIDropDown)ToLua.CheckObject<Ballance2.UI.UIElements.UIDropDown>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			obj.StartSet(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int op_Equality(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.Object arg0 = (UnityEngine.Object)ToLua.ToObject(L, 1);
			UnityEngine.Object arg1 = (UnityEngine.Object)ToLua.ToObject(L, 2);
			bool o = arg0 == arg1;
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Dropdown(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Ballance2.UI.UIElements.UIDropDown obj = (Ballance2.UI.UIElements.UIDropDown)o;
			UnityEngine.UI.Dropdown ret = obj.Dropdown;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index Dropdown on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Text(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Ballance2.UI.UIElements.UIDropDown obj = (Ballance2.UI.UIElements.UIDropDown)o;
			string ret = obj.Text;
			LuaDLL.lua_pushstring(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index Text on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_Text(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Ballance2.UI.UIElements.UIDropDown obj = (Ballance2.UI.UIElements.UIDropDown)o;
			string arg0 = ToLua.CheckString(L, 2);
			obj.Text = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index Text on a nil value");
		}
	}
}

