//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class Ballance2_GameServicesWrap
{
	public static void Register(LuaState L)
	{
		L.BeginEnum(typeof(Ballance2.GameServices));
		L.RegVar("GameMgr", get_GameMgr, null);
		L.RegVar("GameModLoader", get_GameModLoader, null);
		L.RegVar("GameCommandManager", get_GameCommandManager, null);
		L.RegVar("GameUIManager", get_GameUIManager, null);
		L.RegVar("GameCameraManager", get_GameCameraManager, null);
		L.RegFunction("IntToEnum", IntToEnum);
		L.EndEnum();
		TypeTraits<Ballance2.GameServices>.Check = CheckType;
		StackTraits<Ballance2.GameServices>.Push = Push;
	}

	static void Push(IntPtr L, Ballance2.GameServices arg)
	{
		ToLua.Push(L, arg);
	}

	static bool CheckType(IntPtr L, int pos)
	{
		return TypeChecker.CheckEnumType(typeof(Ballance2.GameServices), L, pos);
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_GameMgr(IntPtr L)
	{
		ToLua.Push(L, Ballance2.GameServices.GameMgr);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_GameModLoader(IntPtr L)
	{
		ToLua.Push(L, Ballance2.GameServices.GameModLoader);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_GameCommandManager(IntPtr L)
	{
		ToLua.Push(L, Ballance2.GameServices.GameCommandManager);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_GameUIManager(IntPtr L)
	{
		ToLua.Push(L, Ballance2.GameServices.GameUIManager);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_GameCameraManager(IntPtr L)
	{
		ToLua.Push(L, Ballance2.GameServices.GameCameraManager);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int IntToEnum(IntPtr L)
	{
		int arg0 = (int)LuaDLL.lua_tonumber(L, 1);
		Ballance2.GameServices o = (Ballance2.GameServices)arg0;
		ToLua.Push(L, o);
		return 1;
	}
}

