//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class Ballance2_UI_UIElements_UIButtonWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(Ballance2.UI.UIElements.UIButton), typeof(Ballance2.UI.UIElement));
		L.RegFunction("OnClick", OnClick);
		L.RegFunction("OnInit", OnInit);
		L.RegFunction("StartSet", StartSet);
		L.RegFunction("__eq", op_Equality);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("Text", get_Text, set_Text);
		L.RegVar("onClick", get_onClick, set_onClick);
		L.RegFunction("VoidDelegate", Ballance2_UI_UIElements_UIButton_VoidDelegate);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int OnClick(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			Ballance2.UI.UIElements.UIButton obj = (Ballance2.UI.UIElements.UIButton)ToLua.CheckObject<Ballance2.UI.UIElements.UIButton>(L, 1);
			obj.OnClick();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int OnInit(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			Ballance2.UI.UIElements.UIButton obj = (Ballance2.UI.UIElements.UIButton)ToLua.CheckObject<Ballance2.UI.UIElements.UIButton>(L, 1);
			obj.OnInit();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int StartSet(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			Ballance2.UI.UIElements.UIButton obj = (Ballance2.UI.UIElements.UIButton)ToLua.CheckObject<Ballance2.UI.UIElements.UIButton>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			obj.StartSet(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int op_Equality(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.Object arg0 = (UnityEngine.Object)ToLua.ToObject(L, 1);
			UnityEngine.Object arg1 = (UnityEngine.Object)ToLua.ToObject(L, 2);
			bool o = arg0 == arg1;
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Text(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Ballance2.UI.UIElements.UIButton obj = (Ballance2.UI.UIElements.UIButton)o;
			string ret = obj.Text;
			LuaDLL.lua_pushstring(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index Text on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_onClick(IntPtr L)
	{
		ToLua.Push(L, new EventObject(typeof(Ballance2.UI.UIElements.UIButton.VoidDelegate)));
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_Text(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Ballance2.UI.UIElements.UIButton obj = (Ballance2.UI.UIElements.UIButton)o;
			string arg0 = ToLua.CheckString(L, 2);
			obj.Text = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index Text on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_onClick(IntPtr L)
	{
		try
		{
			Ballance2.UI.UIElements.UIButton obj = (Ballance2.UI.UIElements.UIButton)ToLua.CheckObject(L, 1, typeof(Ballance2.UI.UIElements.UIButton));
			EventObject arg0 = null;

			if (LuaDLL.lua_isuserdata(L, 2) != 0)
			{
				arg0 = (EventObject)ToLua.ToObject(L, 2);
			}
			else
			{
				return LuaDLL.luaL_throw(L, "The event 'Ballance2.UI.UIElements.UIButton.onClick' can only appear on the left hand side of += or -= when used outside of the type 'Ballance2.UI.UIElements.UIButton'");
			}

			if (arg0.op == EventOp.Add)
			{
				Ballance2.UI.UIElements.UIButton.VoidDelegate ev = (Ballance2.UI.UIElements.UIButton.VoidDelegate)arg0.func;
				obj.onClick += ev;
			}
			else if (arg0.op == EventOp.Sub)
			{
				Ballance2.UI.UIElements.UIButton.VoidDelegate ev = (Ballance2.UI.UIElements.UIButton.VoidDelegate)arg0.func;
				obj.onClick -= ev;
			}

			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Ballance2_UI_UIElements_UIButton_VoidDelegate(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);
			LuaFunction func = ToLua.CheckLuaFunction(L, 1);

			if (count == 1)
			{
				Delegate arg1 = DelegateTraits<Ballance2.UI.UIElements.UIButton.VoidDelegate>.Create(func);
				ToLua.Push(L, arg1);
			}
			else
			{
				LuaTable self = ToLua.CheckLuaTable(L, 2);
				Delegate arg1 = DelegateTraits<Ballance2.UI.UIElements.UIButton.VoidDelegate>.Create(func, self);
				ToLua.Push(L, arg1);
			}
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

