//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class Ballance2_Utils_GameConstWrap
{
	public static void Register(LuaState L)
	{
		L.BeginStaticLibs("GameConst");
		L.RegVar("GameVersion", get_GameVersion, null);
		L.RegVar("GameBulidVersion", get_GameBulidVersion, null);
		L.RegVar("GamePlatform", get_GamePlatform, null);
		L.RegVar("GamePlatformIdentifier", get_GamePlatformIdentifier, null);
		L.RegVar("GameScriptBackend", get_GameScriptBackend, null);
		L.EndStaticLibs();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_GameVersion(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, Ballance2.Utils.GameConst.GameVersion);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_GameBulidVersion(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, Ballance2.Utils.GameConst.GameBulidVersion);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_GamePlatform(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, Ballance2.Utils.GameConst.GamePlatform);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_GamePlatformIdentifier(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, Ballance2.Utils.GameConst.GamePlatformIdentifier);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_GameScriptBackend(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, Ballance2.Utils.GameConst.GameScriptBackend);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

