//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class Ballance2_GameBuliderWrap
{
	public static void Register(LuaState L)
	{
		L.BeginStaticLibs("GameBulider");
		L.RegFunction("GetInstance", GetInstance);
		L.RegFunction("RunLuaScriptInAssetGlobal", RunLuaScriptInAssetGlobal);
		L.RegFunction("ExitGameClear", ExitGameClear);
		L.RegFunction("__eq", op_Equality);
		L.RegVar("perfabCube", get_perfabCube, set_perfabCube);
		L.RegVar("perfabEmepty", get_perfabEmepty, set_perfabEmepty);
		L.RegVar("uiHost", get_uiHost, set_uiHost);
		L.RegVar("GlobalLuaState", get_GlobalLuaState, null);
		L.RegVar("LevelHost", get_LevelHost, null);
		L.RegVar("CommandManager", get_CommandManager, null);
		L.RegVar("UIManager", get_UIManager, null);
		L.RegVar("GameMgr", get_GameMgr, null);
		L.RegVar("GameModLoader", get_GameModLoader, null);
		L.RegVar("GameCameraManager", get_GameCameraManager, null);
		L.EndStaticLibs();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetInstance(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 0);
			Ballance2.GameBulider o = Ballance2.GameBulider.GetInstance();
			ToLua.Push(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int RunLuaScriptInAssetGlobal(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 3)
			{
				Ballance2.GameBulider obj = (Ballance2.GameBulider)ToLua.CheckObject<Ballance2.GameBulider>(L, 1);
				Ballance2.GameModPackage arg0 = (Ballance2.GameModPackage)ToLua.CheckObject<Ballance2.GameModPackage>(L, 2);
				string arg1 = ToLua.CheckString(L, 3);
				obj.RunLuaScriptInAssetGlobal(arg0, arg1);
				return 0;
			}
			else if (count == 4)
			{
				Ballance2.GameBulider obj = (Ballance2.GameBulider)ToLua.CheckObject<Ballance2.GameBulider>(L, 1);
				Ballance2.GameModPackage arg0 = (Ballance2.GameModPackage)ToLua.CheckObject<Ballance2.GameModPackage>(L, 2);
				string arg1 = ToLua.CheckString(L, 3);
				string arg2 = ToLua.CheckString(L, 4);
				obj.RunLuaScriptInAssetGlobal(arg0, arg1, arg2);
				return 0;
			}
			else if (count == 5)
			{
				Ballance2.GameBulider obj = (Ballance2.GameBulider)ToLua.CheckObject<Ballance2.GameBulider>(L, 1);
				Ballance2.GameModPackage arg0 = (Ballance2.GameModPackage)ToLua.CheckObject<Ballance2.GameModPackage>(L, 2);
				string arg1 = ToLua.CheckString(L, 3);
				string arg2 = ToLua.CheckString(L, 4);
				string arg3 = ToLua.CheckString(L, 5);
				obj.RunLuaScriptInAssetGlobal(arg0, arg1, arg2, arg3);
				return 0;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to method: Ballance2.GameBulider.RunLuaScriptInAssetGlobal");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int ExitGameClear(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			Ballance2.GameBulider obj = (Ballance2.GameBulider)ToLua.CheckObject<Ballance2.GameBulider>(L, 1);
			obj.ExitGameClear();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int op_Equality(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.Object arg0 = (UnityEngine.Object)ToLua.ToObject(L, 1);
			UnityEngine.Object arg1 = (UnityEngine.Object)ToLua.ToObject(L, 2);
			bool o = arg0 == arg1;
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_perfabCube(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Ballance2.GameBulider obj = (Ballance2.GameBulider)o;
			UnityEngine.GameObject ret = obj.perfabCube;
			ToLua.PushSealed(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index perfabCube on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_perfabEmepty(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Ballance2.GameBulider obj = (Ballance2.GameBulider)o;
			UnityEngine.GameObject ret = obj.perfabEmepty;
			ToLua.PushSealed(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index perfabEmepty on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_uiHost(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Ballance2.GameBulider obj = (Ballance2.GameBulider)o;
			UnityEngine.GameObject ret = obj.uiHost;
			ToLua.PushSealed(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index uiHost on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_GlobalLuaState(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Ballance2.GameBulider obj = (Ballance2.GameBulider)o;
			LuaInterface.LuaState ret = obj.GlobalLuaState;
			ToLua.PushObject(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index GlobalLuaState on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_LevelHost(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Ballance2.GameBulider obj = (Ballance2.GameBulider)o;
			UnityEngine.GameObject ret = obj.LevelHost;
			ToLua.PushSealed(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index LevelHost on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_CommandManager(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Ballance2.GameBulider obj = (Ballance2.GameBulider)o;
			Ballance2.GameCommandManager ret = obj.CommandManager;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index CommandManager on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_UIManager(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Ballance2.GameBulider obj = (Ballance2.GameBulider)o;
			Ballance2.GameUIMgr ret = obj.UIManager;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index UIManager on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_GameMgr(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Ballance2.GameBulider obj = (Ballance2.GameBulider)o;
			Ballance2.GameMgr ret = obj.GameMgr;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index GameMgr on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_GameModLoader(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Ballance2.GameBulider obj = (Ballance2.GameBulider)o;
			Ballance2.GameModLoader ret = obj.GameModLoader;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index GameModLoader on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_GameCameraManager(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Ballance2.GameBulider obj = (Ballance2.GameBulider)o;
			Ballance2.Management.GameCameraManager ret = obj.GameCameraManager;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index GameCameraManager on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_perfabCube(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Ballance2.GameBulider obj = (Ballance2.GameBulider)o;
			UnityEngine.GameObject arg0 = (UnityEngine.GameObject)ToLua.CheckObject(L, 2, typeof(UnityEngine.GameObject));
			obj.perfabCube = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index perfabCube on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_perfabEmepty(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Ballance2.GameBulider obj = (Ballance2.GameBulider)o;
			UnityEngine.GameObject arg0 = (UnityEngine.GameObject)ToLua.CheckObject(L, 2, typeof(UnityEngine.GameObject));
			obj.perfabEmepty = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index perfabEmepty on a nil value");
		}
	}



	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_uiHost(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Ballance2.GameBulider obj = (Ballance2.GameBulider)o;
			UnityEngine.GameObject arg0 = (UnityEngine.GameObject)ToLua.CheckObject(L, 2, typeof(UnityEngine.GameObject));
			obj.uiHost = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index uiHost on a nil value");
		}
	}
}

