//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class GameModPackageWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(GameModPackage), typeof(System.Object));
		L.RegFunction("Dispose", Dispose);
		L.RegFunction("Initialize", Initialize);
		L.RegFunction("HasResPack", HasResPack);
		L.RegFunction("EnumChildResPacks", EnumChildResPacks);
		L.RegFunction("LoadModResPack", LoadModResPack);
		L.RegFunction("LoadFlieResPack", LoadFlieResPack);
		L.RegFunction("UnLoadResPack", UnLoadResPack);
		L.RegFunction("New", _CreateGameModPackage);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("ResPackCount", get_ResPackCount, null);
		L.RegVar("FilePath", get_FilePath, null);
		L.RegVar("Name", get_Name, null);
		L.RegVar("IsZip", get_IsZip, null);
		L.RegVar("ZipFile", get_ZipFile, null);
		L.RegVar("DefaultAssetFindType", get_DefaultAssetFindType, set_DefaultAssetFindType);
		L.RegVar("AssetBundlePath", get_AssetBundlePath, null);
		L.RegVar("BaseAssetPack", get_BaseAssetPack, null);
		L.RegVar("LuaState", get_LuaState, null);
		L.RegVar("NativeMod", get_NativeMod, null);
		L.RegVar("Initnaized", get_Initnaized, null);
		L.RegVar("InitnaizeFailed", get_InitnaizeFailed, null);
		L.RegVar("InitnaizeDsbFile", get_InitnaizeDsbFile, null);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateGameModPackage(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 1 && TypeChecker.CheckTypes<UnityEngine.AssetBundle>(L, 1))
			{
				UnityEngine.AssetBundle arg0 = (UnityEngine.AssetBundle)ToLua.ToObject(L, 1);
				GameModPackage obj = new GameModPackage(arg0);
				ToLua.PushObject(L, obj);
				return 1;
			}
			else if (count == 1 && TypeChecker.CheckTypes<string>(L, 1))
			{
				string arg0 = ToLua.ToString(L, 1);
				GameModPackage obj = new GameModPackage(arg0);
				ToLua.PushObject(L, obj);
				return 1;
			}
			else if (count == 2)
			{
				Helper.ZipFileReader arg0 = (Helper.ZipFileReader)ToLua.CheckObject<Helper.ZipFileReader>(L, 1);
				string arg1 = ToLua.CheckString(L, 2);
				GameModPackage obj = new GameModPackage(arg0, arg1);
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: GameModPackage.New");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Dispose(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			GameModPackage obj = (GameModPackage)ToLua.CheckObject<GameModPackage>(L, 1);
			obj.Dispose();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Initialize(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			GameModPackage obj = (GameModPackage)ToLua.CheckObject<GameModPackage>(L, 1);
			bool arg0 = LuaDLL.luaL_checkboolean(L, 2);
			System.Collections.IEnumerator o = obj.Initialize(arg0);
			ToLua.Push(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int HasResPack(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			GameModPackage obj = (GameModPackage)ToLua.CheckObject<GameModPackage>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			UnityEngine.AssetBundle arg1 = null;
			bool o = obj.HasResPack(arg0, out arg1);
			LuaDLL.lua_pushboolean(L, o);
			ToLua.PushSealed(L, arg1);
			return 2;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int EnumChildResPacks(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			GameModPackage obj = (GameModPackage)ToLua.CheckObject<GameModPackage>(L, 1);
			string o = obj.EnumChildResPacks();
			LuaDLL.lua_pushstring(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int LoadModResPack(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			GameModPackage obj = (GameModPackage)ToLua.CheckObject<GameModPackage>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			bool o = obj.LoadModResPack(arg0);
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int LoadFlieResPack(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			GameModPackage obj = (GameModPackage)ToLua.CheckObject<GameModPackage>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			System.Collections.IEnumerator o = obj.LoadFlieResPack(arg0);
			ToLua.Push(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int UnLoadResPack(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 2)
			{
				GameModPackage obj = (GameModPackage)ToLua.CheckObject<GameModPackage>(L, 1);
				string arg0 = ToLua.CheckString(L, 2);
				bool o = obj.UnLoadResPack(arg0);
				LuaDLL.lua_pushboolean(L, o);
				return 1;
			}
			else if (count == 3)
			{
				GameModPackage obj = (GameModPackage)ToLua.CheckObject<GameModPackage>(L, 1);
				string arg0 = ToLua.CheckString(L, 2);
				bool arg1 = LuaDLL.luaL_checkboolean(L, 3);
				bool o = obj.UnLoadResPack(arg0, arg1);
				LuaDLL.lua_pushboolean(L, o);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to method: GameModPackage.UnLoadResPack");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_ResPackCount(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			GameModPackage obj = (GameModPackage)o;
			int ret = obj.ResPackCount;
			LuaDLL.lua_pushinteger(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index ResPackCount on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_FilePath(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			GameModPackage obj = (GameModPackage)o;
			string ret = obj.FilePath;
			LuaDLL.lua_pushstring(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index FilePath on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Name(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			GameModPackage obj = (GameModPackage)o;
			string ret = obj.Name;
			LuaDLL.lua_pushstring(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index Name on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_IsZip(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			GameModPackage obj = (GameModPackage)o;
			bool ret = obj.IsZip;
			LuaDLL.lua_pushboolean(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index IsZip on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_ZipFile(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			GameModPackage obj = (GameModPackage)o;
			Helper.ZipFileReader ret = obj.ZipFile;
			ToLua.PushObject(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index ZipFile on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_DefaultAssetFindType(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			GameModPackage obj = (GameModPackage)o;
			GameModPackage.GameModPackageAssetFindType ret = obj.DefaultAssetFindType;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index DefaultAssetFindType on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_AssetBundlePath(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			GameModPackage obj = (GameModPackage)o;
			string ret = obj.AssetBundlePath;
			LuaDLL.lua_pushstring(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index AssetBundlePath on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_BaseAssetPack(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			GameModPackage obj = (GameModPackage)o;
			UnityEngine.AssetBundle ret = obj.BaseAssetPack;
			ToLua.PushSealed(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index BaseAssetPack on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_LuaState(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			GameModPackage obj = (GameModPackage)o;
			LuaInterface.LuaState ret = obj.LuaState;
			ToLua.PushObject(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index LuaState on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_NativeMod(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			GameModPackage obj = (GameModPackage)o;
			System.Reflection.Assembly ret = obj.NativeMod;
			ToLua.PushObject(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index NativeMod on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Initnaized(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			GameModPackage obj = (GameModPackage)o;
			bool ret = obj.Initnaized;
			LuaDLL.lua_pushboolean(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index Initnaized on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_InitnaizeFailed(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			GameModPackage obj = (GameModPackage)o;
			bool ret = obj.InitnaizeFailed;
			LuaDLL.lua_pushboolean(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index InitnaizeFailed on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_InitnaizeDsbFile(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			GameModPackage obj = (GameModPackage)o;
			Helper.BFSReader ret = obj.InitnaizeDsbFile;
			ToLua.PushObject(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index InitnaizeDsbFile on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_DefaultAssetFindType(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			GameModPackage obj = (GameModPackage)o;
			GameModPackage.GameModPackageAssetFindType arg0 = (GameModPackage.GameModPackageAssetFindType)ToLua.CheckObject(L, 2, typeof(GameModPackage.GameModPackageAssetFindType));
			obj.DefaultAssetFindType = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index DefaultAssetFindType on a nil value");
		}
	}
}

