//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class GameConstWrap
{
	public static void Register(LuaState L)
	{
		L.BeginStaticLibs("GameConst");
		L.RegVar("GameVersion", get_GameVersion, null);
		L.RegVar("GameBulidVersion", get_GameBulidVersion, null);
		L.EndStaticLibs();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_GameVersion(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, GameConst.GameVersion);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_GameBulidVersion(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, GameConst.GameBulidVersion);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

