//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class Helper_GamePathManagerWrap
{
	public static void Register(LuaState L)
	{
		L.BeginStaticLibs("GamePathManager");
		L.RegFunction("GetResRealPath", GetResRealPath);
		L.RegFunction("GetLevelRealPath", GetLevelRealPath);
		L.RegVar("DEBUG_PATH", get_DEBUG_PATH, null);
		L.RegVar("DEBUG_MODS_PATH", get_DEBUG_MODS_PATH, null);
		L.RegVar("DEBUG_LEVELS_PATH", get_DEBUG_LEVELS_PATH, null);
		L.RegVar("ANDROID_MODS_PATH", get_ANDROID_MODS_PATH, null);
		L.RegVar("ANDROID_LEVELS_PATH", get_ANDROID_LEVELS_PATH, null);
		L.EndStaticLibs();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetResRealPath(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			string arg0 = ToLua.CheckString(L, 1);
			string arg1 = ToLua.CheckString(L, 2);
			string o = Helper.GamePathManager.GetResRealPath(arg0, arg1);
			LuaDLL.lua_pushstring(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetLevelRealPath(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			string arg0 = ToLua.CheckString(L, 1);
			string o = Helper.GamePathManager.GetLevelRealPath(arg0);
			LuaDLL.lua_pushstring(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_DEBUG_PATH(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, Helper.GamePathManager.DEBUG_PATH);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_DEBUG_MODS_PATH(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, Helper.GamePathManager.DEBUG_MODS_PATH);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_DEBUG_LEVELS_PATH(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, Helper.GamePathManager.DEBUG_LEVELS_PATH);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_ANDROID_MODS_PATH(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, Helper.GamePathManager.ANDROID_MODS_PATH);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_ANDROID_LEVELS_PATH(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, Helper.GamePathManager.ANDROID_LEVELS_PATH);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

